# Generated by Django 5.1.7 on 2025-05-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='niveau_choix',
            field=models.CharField(choices=[('débutant', 'Débutant'), ('intérmediaire', 'Intérmediaire'), ('professionnel', 'Professionnel')], default='Débutant', max_length=100),
        ),
    ]
