# Generated by Django 5.1.7 on 2025-06-04 14:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recettes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_title', models.CharField(max_length=60)),
                ('short_description', models.CharField(max_length=400)),
                ('ingredients_list', models.TextField(blank=True)),
                ('preparation_steps', models.TextField(blank=True)),
                ('category_choices', models.CharField(choices=[('appetizers', 'Appetizers'), ('main dishes', 'Main Dishes'), ('soups', 'Soups'), ('salads', 'Salads'), ('desserts', 'Desserts')], default='', max_length=60)),
                ('time_in_minutes', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recettes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.recettes')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_com', models.CharField(max_length=255)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recettes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.recettes')),
            ],
        ),
    ]
