# Generated by Django 5.1.7 on 2025-06-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='valeur_notes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
