# Generated by Django 5.1.7 on 2025-05-19 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaires',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recettes',
            name='etapes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recettes',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
    ]
