# Generated by Django 5.1.7 on 2025-05-21 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0002_commentaires_date_publication_recettes_etapes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recettes',
            name='category_choices',
            field=models.CharField(choices=[('appetizers', 'Appetizers'), ('main dishes', 'Main Dishes'), ('soups', 'Soups'), ('salads', 'Salads'), ('desserts', 'Desserts')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='recettes',
            name='time',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
