# Generated by Django 5.1.7 on 2026-03-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0002_notes_valeur_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recettes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
