# Generated by Django 5.1.7 on 2025-05-21 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0003_recettes_category_choices_recettes_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recettes',
            name='time',
        ),
        migrations.AddField(
            model_name='recettes',
            name='time_in_minutes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
