# Generated by Django 5.1.7 on 2026-03-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0003_recettes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recettes',
            name='moyenne_notes',
            field=models.FloatField(default=0),
        ),
    ]
