# Generated by Django 5.1.7 on 2025-05-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0004_remove_recettes_time_recettes_time_in_minutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recettes',
            old_name='ingredients',
            new_name='ingredients_list',
        ),
        migrations.RenameField(
            model_name='recettes',
            old_name='etapes',
            new_name='preparation_steps',
        ),
        migrations.RenameField(
            model_name='recettes',
            old_name='titre',
            new_name='recipe_title',
        ),
        migrations.RenameField(
            model_name='recettes',
            old_name='description',
            new_name='short_description',
        ),
    ]
