# Generated by Django 5.1.7 on 2025-05-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0005_rename_ingredients_recettes_ingredients_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaires',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
    ]
