# Generated by Django 5.1.7 on 2025-06-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0006_remove_commentaires_user_remove_notes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recettes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
